# Generated by Django 6.0.3 on 2026-03-31 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE tokens
                DROP CONSTRAINT tokens_user_id_9f60f1af_fk_users_id;
    
                ALTER TABLE tokens
                ADD CONSTRAINT tokens_user_id_9f60f1af_fk_users_id
                FOREIGN KEY (user_id)
                REFERENCES users(id)
                ON DELETE CASCADE
                DEFERRABLE INITIALLY DEFERRED;
            """,
            reverse_sql="""
                ALTER TABLE tokens
                DROP CONSTRAINT tokens_user_id_9f60f1af_fk_users_id;
    
                ALTER TABLE tokens
                ADD CONSTRAINT tokens_user_id_9f60f1af_fk_users_id
                FOREIGN KEY (user_id)
                REFERENCES users(id)
                DEFERRABLE INITIALLY DEFERRED;
            """,
        )
    ]
